version: '3.3'

services:
  backend:
    build: 'backend/'
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      VERIFICATION_LINK: ${VERIFICATION_LINK}
      EMAIL_ID: ${EMAIL_ID}
      PASSWORD: ${PASSWORD}
      TOKEN_SECRET: ${TOKEN_SECRET}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    ports:
      - '5000:5000'
    restart: always
    volumes:
      - ./:/usr/src/app
      - ./backend/migrations:/var/lib/postgresql/data
  db:
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    environment:
      POSTGRES_USER: ecom_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecom